name: Deploy HTML to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key on Node
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy HTML to EC2
      run: |
        scp -o StrictHostKeyChecking=no  ./app/index.html ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/